spring:
  application:
    name: contac-sqs-dynamo

  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: https://localhost.localstack.cloud:4566/000000000000/sqs-email

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 4a4049dbda2b6f
    password: ad8398b66bbbe6
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379

app:
  aws:
    sqs:
      email-queue: sqs-email