// TODO Mudar para YML.

spring.application.name=contac-sqs-dynamo

spring.cloud.aws.endpoint=http://localhost:4566
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test

spring.cloud.aws.sqs.endpoint=https://localhost.localstack.cloud:4566/000000000000/sqs-email

app.aws.sqs.email-queue=sqs-email

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=4a4049dbda2b6f
spring.mail.password=ad8398b66bbbe6
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
