spring:
  application:
    name: contac-sqs-dynamo

  cloud:
    aws:
      endpoint: ${AWS_ENDPOINT:http://localhost:4566}
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:test}
        secret-key: ${AWS_SECRET_ACCESS_KEY:test}
      sqs:
        endpoint: ${AWS_SQS_ENDPOINT:http://localhost:4566}

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 1190f941b9011a
    password: 8534ca630aa42d
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  docker:
    compose:
      enabled: ${SPRING_DOCKER_COMPOSE_ENABLED:true}
      lifecycle-management: start_and_stop
      readiness:
        timeout: 2m

app:
  aws:
    sqs:
      email-queue: ${APP_EMAIL_QUEUE:sqs-email}
      email-dlq: ${APP_EMAIL_DLQ_QUEUE:sqs-email-dlq}
