spring.application.name=contac-sqs-dynamo

spring.cloud.aws.endpoint=http://localhost:4566
spring.cloud.aws.region.profile.name=us-east-1
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test

spring.cloud.aws.sqs.endpoint=https://localhost.localstack.cloud:4566/000000000000/sqs-email